services:
  - type: web
    name: p2p-video-chat-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: PORT
        value: 9000
      - key: NODE_ENV
        value: production
